packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  eslint: ^9.18.0

onlyBuiltDependencies:
  - prisma
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
